### ISSUE TITLE
Rewrite the upload script without node.js dependency

### ISSUE THREAD

**Issue by nalexn** [DataDog/datadog-fastlane-plugin#7]
### A feature request

Would it be possible to make the upload script independent of heavy-weight third-party frameworks like node.js?

This would fasten the environment setup on CIs and would make it easier to set up this script as a Build Phase step in Xcode, which is a very common approach used by other crash reporting tools on the market.

**Comment by maxep** [comment]
Hi @nalexn 👋 

Sorry for the very (very) late reply...

This plugin is indeed a wrapper around [datadog-ci](https://github.com/DataDog/datadog-ci) npm package, which is a shared CLI to integrate CI/CD pipelines with various Datadog product.

I might be missing the friction point with node, Node.js is pretty standard and should come pre-installed on most CI providers. With node pre-installed, it should be quick to setup the env.
If you have to install node at every build, then yes it will slow down the setup. But I would suggest to have it pre-installed instead. You can use tools like [nvm](https://github.com/nvm-sh/nvm) to manage the versions.

I'm closing this issue but feel free to contact our [support](https://www.datadoghq.com/support/) to open feature request.
